// Code generated by protoc-gen-go.
// source: op.proto
// DO NOT EDIT!

/*
Package statepb is a generated protocol buffer package.

It is generated from these files:
	op.proto
	snapshot.proto

It has these top-level messages:
	Op
	Cond
	Instruction
	Snapshot
*/
package statepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Op_Type int32

const (
	Op_SET    Op_Type = 0
	Op_DELETE Op_Type = 1
)

var Op_Type_name = map[int32]string{
	0: "SET",
	1: "DELETE",
}
var Op_Type_value = map[string]int32{
	"SET":    0,
	"DELETE": 1,
}

func (x Op_Type) String() string {
	return proto.EnumName(Op_Type_name, int32(x))
}
func (Op_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Cond_Type int32

const (
	Cond_KEY_EXISTS      Cond_Type = 0
	Cond_NOT_KEY_EXISTS  Cond_Type = 1
	Cond_VALUE_EQUAL     Cond_Type = 2
	Cond_NOT_VALUE_EQUAL Cond_Type = 3
	Cond_INDEX_EQUAL     Cond_Type = 4
	Cond_NOT_INDEX_EQUAL Cond_Type = 5
)

var Cond_Type_name = map[int32]string{
	0: "KEY_EXISTS",
	1: "NOT_KEY_EXISTS",
	2: "VALUE_EQUAL",
	3: "NOT_VALUE_EQUAL",
	4: "INDEX_EQUAL",
	5: "NOT_INDEX_EQUAL",
}
var Cond_Type_value = map[string]int32{
	"KEY_EXISTS":      0,
	"NOT_KEY_EXISTS":  1,
	"VALUE_EQUAL":     2,
	"NOT_VALUE_EQUAL": 3,
	"INDEX_EQUAL":     4,
	"NOT_INDEX_EQUAL": 5,
}

func (x Cond_Type) String() string {
	return proto.EnumName(Cond_Type_name, int32(x))
}
func (Cond_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Op struct {
	Type  Op_Type `protobuf:"varint,1,opt,name=type,enum=statepb.Op_Type" json:"type,omitempty"`
	Key   string  `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Value []byte  `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Op) Reset()                    { *m = Op{} }
func (m *Op) String() string            { return proto.CompactTextString(m) }
func (*Op) ProtoMessage()               {}
func (*Op) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Cond struct {
	Type  Cond_Type `protobuf:"varint,1,opt,name=type,enum=statepb.Cond_Type" json:"type,omitempty"`
	Key   string    `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Value []byte    `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Index uint64    `protobuf:"varint,4,opt,name=index" json:"index,omitempty"`
}

func (m *Cond) Reset()                    { *m = Cond{} }
func (m *Cond) String() string            { return proto.CompactTextString(m) }
func (*Cond) ProtoMessage()               {}
func (*Cond) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Instruction struct {
	Conditions []*Cond `protobuf:"bytes,1,rep,name=conditions" json:"conditions,omitempty"`
	Operations []*Op   `protobuf:"bytes,2,rep,name=operations" json:"operations,omitempty"`
}

func (m *Instruction) Reset()                    { *m = Instruction{} }
func (m *Instruction) String() string            { return proto.CompactTextString(m) }
func (*Instruction) ProtoMessage()               {}
func (*Instruction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Instruction) GetConditions() []*Cond {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *Instruction) GetOperations() []*Op {
	if m != nil {
		return m.Operations
	}
	return nil
}

func init() {
	proto.RegisterType((*Op)(nil), "statepb.Op")
	proto.RegisterType((*Cond)(nil), "statepb.Cond")
	proto.RegisterType((*Instruction)(nil), "statepb.Instruction")
	proto.RegisterEnum("statepb.Op_Type", Op_Type_name, Op_Type_value)
	proto.RegisterEnum("statepb.Cond_Type", Cond_Type_name, Cond_Type_value)
}

func init() { proto.RegisterFile("op.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x91, 0xc1, 0x4e, 0xf2, 0x40,
	0x10, 0xc7, 0xbf, 0xb6, 0x0b, 0x7c, 0x0e, 0x0a, 0xcd, 0xe8, 0xa1, 0x89, 0x17, 0xd3, 0x18, 0x43,
	0x62, 0xec, 0x01, 0x9f, 0x80, 0xc8, 0x1e, 0x88, 0x04, 0xe2, 0xb6, 0x18, 0x3c, 0x35, 0x05, 0xf6,
	0xd0, 0x68, 0xba, 0x9b, 0x76, 0x21, 0xf2, 0xbe, 0x3e, 0x88, 0xbb, 0x6d, 0x35, 0xcb, 0xd5, 0xdb,
	0xce, 0xef, 0xff, 0xdb, 0xcc, 0x4c, 0x06, 0xfe, 0x0b, 0x19, 0xc9, 0x52, 0x28, 0x81, 0xbd, 0x4a,
	0x65, 0x8a, 0xcb, 0x4d, 0x28, 0xc0, 0x5d, 0x4a, 0xbc, 0x05, 0xa2, 0x8e, 0x92, 0x07, 0xce, 0x8d,
	0x33, 0x1a, 0x8c, 0xfd, 0xa8, 0x4d, 0xa3, 0xa5, 0x8c, 0x12, 0xcd, 0x59, 0x9d, 0xa2, 0x0f, 0xde,
	0x3b, 0x3f, 0x06, 0xae, 0x96, 0xce, 0x98, 0x79, 0xe2, 0x15, 0x74, 0x0e, 0xd9, 0xc7, 0x9e, 0x07,
	0x9e, 0x66, 0xe7, 0xac, 0x29, 0xc2, 0x6b, 0x20, 0xe6, 0x17, 0xf6, 0xc0, 0x8b, 0x69, 0xe2, 0xff,
	0x43, 0x80, 0xee, 0x94, 0xce, 0x69, 0x42, 0x7d, 0x27, 0xfc, 0x72, 0x80, 0x3c, 0x89, 0x62, 0x87,
	0x77, 0x27, 0x3d, 0xf1, 0xb7, 0xa7, 0x09, 0xff, 0xd0, 0xd5, 0xd0, 0xbc, 0xd8, 0xf1, 0xcf, 0x80,
	0x68, 0x4a, 0x58, 0x53, 0x84, 0x87, 0x76, 0x96, 0x01, 0xc0, 0x33, 0x7d, 0x4b, 0xe9, 0x7a, 0x16,
	0x27, 0xb1, 0x1e, 0x09, 0x61, 0xb0, 0x58, 0x26, 0xa9, 0xc5, 0x1c, 0x1c, 0x42, 0xff, 0x75, 0x32,
	0x5f, 0xd1, 0x94, 0xbe, 0xac, 0x26, 0x73, 0xdf, 0xc5, 0x4b, 0x18, 0x1a, 0xc9, 0x86, 0x9e, 0xb1,
	0x66, 0x8b, 0x29, 0x5d, 0xb7, 0x80, 0xfc, 0x58, 0x36, 0xec, 0x84, 0xb9, 0xb6, 0x8a, 0x4a, 0x95,
	0xfb, 0xad, 0xca, 0x45, 0x81, 0x0f, 0x00, 0x5b, 0xbd, 0x57, 0x6e, 0x8a, 0x4a, 0xaf, 0xec, 0x8d,
	0xfa, 0xe3, 0x8b, 0x93, 0x95, 0x99, 0x25, 0xe0, 0x3d, 0x80, 0x90, 0xbc, 0xcc, 0x1a, 0xdd, 0xad,
	0xf5, 0xbe, 0x75, 0x15, 0x66, 0xc5, 0x9b, 0x6e, 0x7d, 0xd2, 0xc7, 0xef, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xd4, 0x57, 0x6f, 0x89, 0xde, 0x01, 0x00, 0x00,
}
